Repository mingxoxo/minishell, pull requests merged in 2023-01, with the labels that each got.

#14 [add] return.h
  includes/return.h
Labels: 💻 Implement

#24 [add] set_env
  builtin/cd.c
  ds_envp/add.c
  ds_envp/cast_arr.c
  ds_envp/cast_list.c
  ds_envp/init.c
  ds_envp/set.c
  includes/ds_envp.h
Labels: 🐞 Bug, 🛠 Refactor

#23 implement : #22/Makefile과 main 함수 추가
  Makefile
  main.c
Labels: 💻 Implement

#28 [modify] if value is NULL
  ds_envp/cast_arr.c
  ds_envp/delete.c
  ds_envp/init.c
  ds_envp/set.c
  includes/ds_envp.h
Labels: 🛠 Refactor

#27 implement : #26/readline 기능 추가
  Makefile
  main.c
Labels: 💻 Implement

#36 bug : #35/WWW 플래그 에러 처리
  Makefile
  builtin/cd.c
  builtin/echo.c
  builtin/env.c
  main.c
Labels: 🐞 Bug

#39 #38 token linked-list를 활용하여 binary tree 생성
  Makefile
  ds_tree/add.c
  ds_tree/delete.c
  ds_tree/init.c
  ds_tree/search.c
  includes/ds_tree.h
  includes/make_tree.h
  includes/token.h
  main.c
  parsing/check.c
  parsing/make_node.c
  parsing/make_tree.c
  parsing/token.c
Labels: 💻 Implement

#41 #38 binary tree 생성 시 괄호 leak 해결
  ds_tree/delete.c
  main.c
  parsing/check.c
  parsing/token.c
Labels: 🐞 Bug, 🛠 Refactor

#43 #42 트리 생성 시 괄호의 올바른 짝을 찾도록 bug 수정
  Makefile
  includes/make_tree.h
  main.c
  parsing/check_tnode.c
  parsing/check_type.c
Labels: 🐞 Bug, 🛠 Refactor

#44 #40 implement token linked list 형식 체크
  Makefile
  includes/make_tree.h
  main.c
  parsing/check_syntax.c
Labels: 💻 Implement

#45 Implement: #37/실행파트 구현
  Makefile
  execute/argv.c
  execute/child.c
  execute/execute.c
  execute/heredoc.c
  execute/heredoc_util.c
  execute/path.c
  execute/preprocess.c
  execute/redirection.c
  execute/util.c
  includes/execute.h
  main.c
Labels: 💻 Implement

#51 Implement: #50/내장함수 적용
  Makefile
  builtin/cd.c
  builtin/echo.c
  builtin/env.c
  builtin/exit.c
  builtin/export.c
  builtin/print_export.c
  builtin/pwd.c
  builtin/unset.c
  execute/builtin.c
  execute/child.c
  execute/execute.c
  includes/builtin.h
  includes/execute.h
  main.c
Labels: 🛠 Refactor, 💻 Implement

#52 Refactor : #30/export - 함수 인자 변경
  builtin/export.c
  builtin/print_export.c
  ds_envp/cast_list.c
  execute/builtin.c
  includes/ds_envp.h
  main.c
Labels: 🛠 Refactor

#55 Bug : #53/선언되지 않은 환경변수 에러
  execute/child.c
  execute/path.c
Labels: 🐞 Bug, 🛠 Refactor

#56 Bug: #54/터미널 세팅 복구
  main.c
Labels: 🐞 Bug

#58 Bug : #46/부모 프로세스 시그널 핸들링
  execute/child.c
  includes/minishell.h
  main.c
  terminal.c
Labels: 🐞 Bug, 💻 Implement

#61 Implement : #48/implement 환경변수 치환
  Makefile
  includes/make_tree.h
  includes/token.h
  main.c
  parsing/arr.c
  parsing/check_syntax.c
  parsing/check_type.c
  parsing/subst_env.c
  parsing/subst_env_first.c
  parsing/subst_env_lst.c
  parsing/subst_env_second.c
  parsing/token.c
Labels: 🐞 Bug, 💻 Implement

#62 Bug : #60/heredoc 오류 수정
  builtin/env.c
  execute/builtin.c
  execute/child.c
Labels: 🐞 Bug

#65 Implement : #63/#64 redirection 환경변수 치환/환경변수 치환 생략
  parsing/subst_env.c
Labels: 🛠 Refactor, 💻 Implement

#66 Implement : #57/따옴표 제거
  Makefile
  includes/make_tree.h
  includes/minishell.h
  parse.c
  parsing/del_quote.c
  parsing/subst_env_lst.c
Labels: 💻 Implement

#67 Refactor : #59/main 함수 수정
  Makefile
  builtin/exit.c
  execute/builtin.c
  execute/child.c
  execute/execute.c
  includes/execute.h
  includes/make_tree.h
  includes/minishell.h
  main.c
  parse.c
  parsing/del_quote.c
  parsing/subst_env_lst.c
  terminal.c
Labels: 🐞 Bug, 🛠 Refactor

#68 Implement : 연산자 적용
  execute/execute.c
  includes/execute.h
  main.c
Labels: 💻 Implement

#72 Bug : #71/[fix] 환경변수 head 삭제 시 envp 연결 오류
  ds_envp/delete.c
Labels: 🐞 Bug

#74 Implement : #69/환경변수 초기화 기능 추가
  execute/child.c
  execute/execute.c
  includes/minishell.h
  main.c
  terminal.c
Labels: 🛠 Refactor, 💻 Implement

#76 Bug : #73/디렉토리 명령어 에러 수정
  execute/child.c
  execute/path.c
  execute/util.c
  includes/execute.h
Labels: 🐞 Bug

#77 Implement : #75/substitute wildcard * → �
  Makefile
  includes/make_tree.h
  parse.c
  parsing/subst.c
  parsing/subst_env.c
  parsing/subst_wildcard.c
Labels: 💻 Implement

#79 Refactor : #70/heredoc - 시그널 처리
  Makefile
  execute/builtin.c
  execute/execute.c
  execute/heredoc.c
  execute/heredoc_util.c
  includes/minishell.h
  signal.c
  terminal.c
Labels: 🛠 Refactor, 💻 Implement

#80 implement : minishell 시작 시 tmp 디렉토리 생성 기능 추가
  execute/heredoc_util.c
  includes/minishell.h
  main.c
  terminal.c
Labels: 💻 Implement

#81 Implement : #78/와일드카드 검색패턴 적용
  Makefile
  ds_tree/add.c
  ds_tree/init.c
  includes/make_tree.h
  parse.c
  parsing/subst.c
  parsing/subst_wildcard.c
  parsing/wildcard.c
Labels: 💻 Implement

#82 Implement : 파이프 에러 수정
  execute/child.c
  parsing/wildcard.c
Labels: 🐞 Bug, 🛠 Refactor

#85 Refactor : #83/parsing error 종료 코드 설정
  parse.c
Labels: 🛠 Refactor

#86 fix : #84/잘못된 명령어를 제대로 구분하지 못하는 오류 수정
  execute/builtin.c
Labels: 🐞 Bug

#87 Bug : 기타 오류 수정
  Makefile
  execute/child.c
  execute/execute.c
  main.c
Labels: 🐞 Bug, 🛠 Refactor

#89 Bug: #88/명령어가 들어오지 않을 때 syntax error로 처리
  builtin/cd.c
  builtin/exit.c
  builtin/export.c
  execute/child.c
  parse.c
  parsing/check_syntax.c
Labels: 🐞 Bug, 🛠 Refactor

#90 Refactor : 기타 수정 사항
  execute/redirection.c
  main.c
  parsing/subst_env_first.c
Labels: 🛠 Refactor

#91 Refactor : 최종 수정사항 반영
  ds_envp/cast_arr.c
  ds_envp/cast_list.c
  ds_envp/delete.c
  ds_envp/init.c
  ds_envp/search.c
  ds_envp/set.c
  ds_tree/add.c
  ds_tree/delete.c
  ds_tree/init.c
  ds_tree/search.c
  execute/heredoc_util.c
  includes/ds_envp.h
  includes/minishell.h
  main.c
  terminal.c
Labels: 🐞 Bug, 🛠 Refactor
